version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - app-server

  app-server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - app-db
      # - redis

  app-db:
    image: postgres:16
    restart: always
    volumes:
      - ./data/app-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${APPDB_NAME}
      POSTGRES_USER: ${APPDB_USER}
      POSTGRES_PASSWORD: ${APPDB_PASSWORD}

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
# volumes:
#   db-data:
